version: '3.9'


services:

  cpp:
    build:
      context: $ROOT/cpp/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
    env_file: 
      - common.env
    image: kagemeka/cp:cpp
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
      - type: bind
        source: $ROOT/cpp/
        target: /root/cp/
    working_dir: /root/cp/
      
  cs:
    build:
      context: $ROOT/cs/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
    env_file: 
      - common.env
    image: kagemeka/cp:cs
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/cs/
        target: /root/cp/
    working_dir: /root/cp/

  dart:
    build:
      context: $ROOT/dart/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
    env_file: 
      - common.env
    image: kagemeka/cp:dart
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: $ROOT/dart/
        target: /root/cp/
    working_dir: /root/cp/
   
  go:
    build:
      context: $ROOT/go/env/
      dockerfile:
        "docker/\
        Dockerfile.alpine"
    env_file: 
      - common.env
    image: kagemeka/cp:go
    tty: true
    volumes:
      - type: bind
        source: $ROOT/go/
        target: /root/cp/
    working_dir: /root/cp/

  jl:
    build:
      context: $ROOT/jl/env/
      dockerfile:
        "docker/\
        Dockerfile.alpine"
    env_file: 
      - common.env
    image: kagemeka/cp:jl
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/jl/
        target: /root/cp/
    working_dir: /root/cp/

  kt:
    build:
      context: $ROOT/kt/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
    env_file: 
      - common.env
    image: kagemeka/cp:kt
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/kt/
        target: /root/cp/
    working_dir: /root/cp/
    
  node:
    build:
      context: $ROOT/node/env/
      dockerfile:
        "docker/\
        Dockerfile.alpine"
    env_file: 
      - common.env
    image: kagemeka/cp:node
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/node/
        target: /root/cp/
    working_dir: /root/cp/
    
  py:
    build:
      context: $ROOT/py/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
    env_file: 
      - common.env
    image: kagemeka/cp:py
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: $ROOT/py/
        target: /root/cp/
    working_dir: /root/cp/
  
  rs:
    build:
      context: $ROOT/rs/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
    env_file: 
      - common.env
    image: kagemeka/cp:rs
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/rs/
        target: /root/cp/
    working_dir: /root/cp/
  
  swift:
    build:
      context: $ROOT/swift/env/
      dockerfile:
        "docker/\
        Dockerfile.ubuntu"
      target: artifact
    env_file: 
      - common.env
    image: kagemeka/cp:swift
    privileged: true
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/swift/
        target: /root/cp/
    working_dir: /root/cp/
     
  ts:
    build:
      context: $ROOT/ts/env/
      dockerfile:
        "docker/\
        Dockerfile.alpine"
    env_file: 
      - common.env
    image: kagemeka/cp:ts
    tty: true
    volumes:
      - type: tmpfs
        target: /tmp/
      - type: bind
        source: $ROOT/ts/
        target: /root/cp/
    working_dir: /root/cp/
      