version: '3.9'

services:
  main:
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    # image: kagemeka/$PROJECT_NAME:$PROJECT_VERSION

    image: ubuntu:latest
    # env_file:
    #   - common.env
    restart: on-failure
    privileged: true
    tty: true
    volumes:
      - type: bind
        source: $PROJECT_ROOT
        target: /root/$PROJECT_NAME
        volume:
          nocopy: true
        read_only: false
      - type: bind
        bind:
          propagation: rprivate
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: $GIT_CONFIG_PATH
        target: /etc/gitconfig
        volume:
          nocopy: true
        read_only: true
