FROM ubuntu:20.04
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root/
ARG GOVER=1.16.5
RUN \
  apt -q=2 update \
  && apt install -y \
  apt-utils \
  wget \ 
  && wget -qO - \
  https://dl.google.com/go/go${GOVER}.linux-amd64.tar.gz \
  | tar -xzC /usr/local/ \
  && echo 'export GOPATH=/usr/local/go' >> ~/.bashrc \
  && source ~/.bashrc \
  && echo 'export PATH=$PATH:$GOPATH/bin' >> ~/.bashrc