FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root/ 
SHELL ["/bin/bash", "-c"]
ARG MAJOR=1
ARG MINOR=6
ARG PATCH=1
ARG MM_VER=${MAJOR}.${MINOR}
ARG VER=${MM_VER}.${PATCH}
RUN \
  apt update -q=2 \
  && apt install -yq=2 \
  apt-utils \
  wget \
  && wget -O - \
  https://julialang-s3.julialang.org/bin/linux/x64/${MM_VER}/julia-${VER}-linux-x86_64.tar.gz \
  | tar \
  -xvzC /usr/local \
  --transform=s/-${VER}// \
  && ln -fns \
  /usr/local/julia/bin/julia \
  /usr/bin/julia