FROM ubuntu:20.04 AS java-stage
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root/
RUN \
  apt -q=2 update \
  && apt install -yq=2 \
  apt-utils \
  default-jre


FROM java-stage AS artifact
RUN \
  apt install -yq=2 \
  curl \
  unzip \
  zip \
  && curl -s https://get.sdkman.io | bash \
  && echo \
  'source $HOME/.sdkman/bin/sdkman-init.sh' \
  >> ~/.bashrc \
  && source ~/.bashrc \
  && source $HOME/.sdkman/bin/sdkman-init.sh \
  && sdk install kotlin 